### PR TITLE
Feature root element

### LINKED ISSUE #400: Turbolinks breaks ad viewability trackers
We use Turbolinks on our ad-supported site and have recently suffered from a bug that prevents ad viewability trackers to fire after Turbolinks visits. Specifically, it is the [Active View](https://support.google.com/dfp_premium/answer/6123557?hl=en) tracker that DFP uses.

Removing Turbolinks, we see ads behaving as expected. We also have some pages that refresh ads throughout the lifetime of the single page; these ad loads behave as expected, too. Only on Turbolinks visits do these trackers not fire properly.

This is a somewhat recent development. It seems correlated with a GPT.js release, and we're reaching out to Google to see if there is anything they are aware of on their end that may have broken Turbolinks usage.

Our hypothesis is that Turbolinks destroying the whole `<body>` tag between page views is the culprit. I have tried adding an opt-in feature to Turbolinks that only swaps a portion of the `<body>`. This seems to resolve the issue we are facing, though it's not entirely clear yet if this might be introducing other subtle bugs.

Has anybody else come across this specific issue with Active View trackers? Or similar issues with third party code that breaks when the `<body>` is wholesale replaced?

### PR DESCRIPTION
**Pull request by ahaurw01**
Fixes #400 

New opt-in feature: annotating a new page's element with `data-turbolinks-root` will swap in only that element and not the entire `body`, provided that the previous page also had a `data-turbolinks-root` element.

This is an attempt to play nice with DFP's Active View tracker which seems to break when the entire `body` is replaced between page views.

This feature is sort of the opposite side of the coin of `data-turbolinks-permanent`. There would seem to be plenty of cases where third party logic inserts elements in the DOM that you'd want to carry over to future page views.

Has discussion of this feature come up previously? Any reasons that this is obviously a bad idea?

This feature seems to break snapshot caching since the body is mutated instead of plucked away entirely. Any advice on a simple way to allow caching to occur with this new feature?

### CODE REVIEW

**Comment by MidnightWonderer** [comment]
Should `data-turbolinks-root` be a selector configuration passed to `Turbolinks.start()` instead?

**Comment by boqusi** [comment]
That would be very helpful. Turbolinks doesn't let my animations (e.g. closing a drawer) finish because it replaces the whole document.body, and using this fork is currently the only solution I got to work.

**Comment by domchristie** [comment]
Hi @ahaurw01 thanks for this. Replacing a custom DOM element was discussed in #43, and it was decided that Turbolinks should stick to swapping out the `<body>` to maintain simplicity. Thanks again.

**Comment by ianwhite** [comment]
I have the same use case as @metaskills.  

Because of the way browsers treat iFrames, it's not possible to move them out and back into the body after replace [see this SO answer](https://stackoverflow.com/questions/8318264/how-to-move-an-iframe-in-the-dom-without-losing-its-state#answer-8318401)

This means you need to setup/teardown any such scripts on each turbolinks body replacement, but there are often no APIs for this.

For example zendesk has API methods for SPAs (like changing the current URL and auth info) but has no setup/teardown api.

A `data-turbolinks-root` attribute, which is opt-in, would solve my issue, and possibly some of the issues above.  It would also not affect the default behaviour.

Is it possible to reopen this issue?

**Comment by ahaurw01** [comment]
@ianwhite if it helps, we've been using the latest commit of https://github.com/spanishdict/turbolinks in production for the last several months which contains this feature and it has performed well for us. It is out of date with this repo by now and would require some work to get up to speed after the typescript rewrite.

**Comment by ianwhite** [comment]
@ahaurw01 I've written my own fork, which is updated for TypeScript, but uses a configuration option to enable the feature.  https://github.com/ianwhite/turbolinks

**Comment by wkasem** [comment]
@ianwhite how can i install your version of turboklinks through npm ?

**Comment by ianwhite** [comment]
> @ianwhite how can i install your version of turboklinks through npm ?

Hi @wkasem the npm repository is @ian2w/turbolinks

**Comment by wkasem** [comment]
> @ian2w

Sorry but can't find it :/
https://www.npmjs.com/search?q=%40ian2w%2Fturbolinks

**Comment by ianwhite** [comment]
Apologies, here it is: https://www.npmjs.com/package/@ian2w/turbolinks

**Comment by wkasem** [comment]
> Apologies, here it is: https://www.npmjs.com/package/@ian2w/turbolinks

Thanks a lot

**Comment by ianwhite** [comment]
I've opened the issue tracker on https://github.com/ianwhite/turbolinks so we can stop spamming this thread.

**Pull request closed without merging**
