### PR TITLE
Add UMD support. Fixes #91

### LINKED ISSUE #91: "Uncaught ReferenceError: Turbolinks is not defined" when required with Browserify
We are using Browserify to build our front-end assets. We successfully installed the `turbolinks` npm package and compiled the assets, but when the page loads in the browser, `Uncaught ReferenceError: Turbolinks is not defined` is raised in the package code `dist/turbolinks.js` at `Turbolinks.copyObject=function(t){var e,r,n;r={}; ...`

Oddly, we are able to use the package if we paste the raw `dist/turbolinks.js` into a script tag in the html head.

Are there any steps we need to take in order to get this package to work with Browserify? If Browserify is currently unsupported, are you open to pull requests to introduce support? Any pointers would be appreciated.

Thanks

### PR DESCRIPTION
**Pull request by javan**
Define UMD module for Turbolinks to support script / module build tools like webpack, browserify, require.js, etc.

### CODE REVIEW

**Comment by sstephenson** [comment]
We’ll need to update [the documentation](https://github.com/turbolinks/turbolinks#installation-using-webpack) too.

**Comment by javan** [comment]
What do you think about removing the [Installation Using Webpack](https://github.com/turbolinks/turbolinks#installation-using-webpack) documentation since it Just Works now?

**Comment by sstephenson** [comment]
I’m fine with removing the Webpack-specific parts, but we should still have a parallel set of instructions for using Turbolinks as a module. You still have to install the package and require it somewhere.

**Comment by javan** [comment]
Updated the docs

**Comment by javan** [comment]
FYI, I confirmed the compiled .js works normally with `<script src="turbolinks.js"></script>` and with webpack and browserify:
```js
(function() {
  var Turbolinks = require("./turbolinks");
  console.log("local var Turbolinks =", Turbolinks); // defined
})()

addEventListener("DOMContentLoaded", function() {
  console.log("widow.Turbolinks =", window.Turbolinks) // undefined
})
```

**Comment by TSMMark** [comment]
As a Browserify user, I thank you! :+1:

**Comment by sstephenson** [comment]
Thanks for making this possible @javan! 💝🎉

**Pull request merged**
