### PR TITLE
Check for window.turbolinksHistory first and then use window.history if not exist

### PR DESCRIPTION
**Pull request by TSMMark**
Corresponding Issue: #150

### CODE REVIEW

**Comment by sstephenson** [comment]
Thanks for the pull request. Can you please point me to a page demonstrating the problem this solves? I’m skeptical that Turbolinks and react-router will ever be compatible.

**Comment by sstephenson** [comment]
Also, let’s please avoid hostile or aggressive [commit messages](https://github.com/turbolinks/turbolinks/pull/151/commits/1a8c4e031c1100f6a103cd92e10d411828510c72). Thanks.

**Comment by TSMMark** [comment]
I won't be able to include a link to a page, but I can post our relevant js:

```js
var _ = require("lodash");
var ReactRouter = require("react-router");

var removeDomainAndProtocol = function(url) {
  return url.replace(/^.*\/\/[^\/]+/, "");
}

// API Adapter to handle turbolinks & react-router.
var turbolinksHistory = _.extend({}, ReactRouter.browserHistory);

turbolinksHistory.pushState = function(_turbolinks, _null, urls) {
  turbolinksHistory.push(removeDomainAndProtocol(urls.requestURL));
}
turbolinksHistory.replaceState = function(_turbolinks, _null, urls) {
  turbolinksHistory.replace(removeDomainAndProtocol(urls.requestURL));
}

module.exports = window.turbolinksHistory = turbolinksHistory;
```

```jsx
// Router uses turbolinksHistory
var turbolinksHistory = require("./turbolinksHistory");
<Router history={turbolinksHistory}>
  {Routes}
</Router>
```

**Comment by TSMMark** [comment]
Bugs were discovered with the approach. We did get react-router and turbolinks functioning together though. For the record, future developer who has stumbled upon this, you have to unmount and then re-mount your react-router on every turbolinks navigation. You can not use react-router `Link` components, etc, nor can you use any react-router navigation functions.

You also must create a new history object on every page load, kind of like this:

```jsx
// On every turbolinks:before-visit
var onTurbolinksPageVisit = function () {
  var createHistory = require("history").createHistory;
  // We have to create a new history every page navigation because of turbolinks.
  // You see, turbolinks makes calls to the window.history directly, and react-router
  // history has no way of knowing about it. If you don't create a new history object
  // every time, the history object in memory will contain cached data that makes
  // react-router believe that it is still on the previous page.
  var history = useRouterHistory(createHistory)({});
  var routerComponent = (
    <Router history={history}>
      {Routes}
    </Router>
  );
  // ... Handle the mounting of routerComponent
}
```

**Pull request closed without merging**
